/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        HelloNamelist classUnderTest = new HelloNamelist();
        assertEquals(classUnderTest.getGreeting(new String[] {""}),"Hello ", "app greets noone");
    }
    
    @Test public void appHasAGreeting2() {
        HelloNamelist classUnderTest = new HelloNamelist();
        assertEquals(classUnderTest.getGreeting(new String[] {"my","test"}),"Hello mytest", "app greets noone");
    }
}
